In [1]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [2]:
print(f"iris_datasets keys : {iris_dataset.keys()}")

iris_datasets keys : dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [3]:
print(f"{iris_dataset['DESCR'][:193]}\n")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre



In [4]:
print(f"target : {iris_dataset['target_names']}")

target : ['setosa' 'versicolor' 'virginica']


In [5]:
print(f"feature : {iris_dataset['feature_names']}")

feature : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print(f"data type : {type(iris_dataset['data'])}")

data type : <class 'numpy.ndarray'>


In [7]:
print(f"data size : {iris_dataset['data'].shape}")

data size : (150, 4)


In [8]:
print(f"first 5 rows: \n {iris_dataset['data'][:5]}")

first 5 rows: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [9]:
print(f"target type : {type(iris_dataset['target'])}")

target type : <class 'numpy.ndarray'>


In [10]:
print(f"target size : {iris_dataset['target'].shape}")

target size : (150,)


In [11]:
#0(setosa), 1(versicolor), 2(virginica)
print(f"target :\n {iris_dataset['target']}")

target :
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'],
    random_state=42
)

In [13]:
print(f"X_train size: {X_train.shape}")
print(f"y_train size: {y_train.shape}")

X_train size: (112, 4)
y_train size: (112,)


In [14]:
print(f"X_test size: {X_test.shape}")
print(f"y_test size: {y_test.shape}")

X_test size: (38, 4)
y_test size: (38,)
